"""Tables 1-3 of the article as LaTeX fragments from the generated data only (generated/data/).
Usage: python3 analysis/tables/src/make_tables.py [--check].  Output: tables/T1-regimes.tex, T2-structure.tex, T3-tests.tex,
tables/TABLES-MANIFEST.json. Every number and status comes from the CSVs; the only hand-written cell text is the
non-numeric descriptor vocabulary in DESCRIPTORS (regime display names, metered quantity, priced components), sourced
to the frozen C1 documents named there. No scientific quantity is computed here.
Generator paths in output stamps and in TABLES-MANIFEST.json are relative to analysis/."""
import csv, hashlib, io, json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]; DATA = ROOT / 'generated' / 'data'; OUT = ROOT / 'tables'
inputs = {}
def read(name):
    b = (DATA / name).read_bytes(); inputs[f'generated/data/{name}'] = hashlib.sha256(b).hexdigest()
    return list(csv.DictReader(io.StringIO(b.decode('utf-8'))))
def md(s):   # strip markdown from frozen toolchain cells; escape for LaTeX
    s = s.replace('**', '').replace('`', '')
    return s.replace('&', '\\&').replace('%', '\\%').replace('_', '\\_').replace('#', '\\#')

# Non-numeric descriptor vocabulary (sources: C1 03-factors-and-configurations.md §1, 04-toolchain-matrix.md, 06-model-equations.md,
# 07-parameter-ledger.csv symbol meanings). Pins and roles are NOT here: they are read from t1_toolchain_rows.csv.
DESCRIPTORS = {
    'evm-osaka': ('EVM Osaka', 'EVM execution', 'osaka (CORE)', 'gas of the direct verifier transaction ($Y_{\\mathrm{dir}}$)',
                  'EC precompile gas (ecAdd, ecMul, pairing); calldata gas; execution gas incl.\\ Keccak'),
    'eravm-29': ('EraVM v29', 'EraVM node', 'protocol 29 (CORE)', 'computational gas from the refund trace ($Y_{\\mathrm{dir}}$)',
                 'per-call precompile frame costs (ecAdd, ecMul, pairing); Keccak rounds; execution'),
    'zkos-v32': ('ZKsync OS v32', 'ZKsync OS node', 'v32.0', 'gas $=$ $\\max(\\text{EVM gas},$ $\\lfloor\\text{native}/\\mathrm{npg}\\rfloor)$ with npg $=100$ ($Y_{\\mathrm{dir}}$); native ($N_{\\mathrm{dir}}$)',
                 'native resource prices of the ZKsync OS VM per operation (EC precompiles, Keccak, copying, opcode steps)'),
    'eravm-27': ('EraVM v27', 'EraVM node', '27 (VALIDATION)', 'computational gas from the refund trace ($Y_{\\mathrm{dir}}$)',
                 'as EraVM v29, with the historical protocol-27 precompile costs'),
}
ROLE_FROM_PIN = {'osaka (CORE)': 'CORE', 'protocol 29 (CORE)': 'CORE', 'v32.0': 'CORE', '27 (VALIDATION)': 'VALIDATION'}

def t1():
    rows = {r['role']: r for r in read('t1_toolchain_rows.csv')}
    out = ['% GENERATED by tables/src/make_tables.py from generated/data/t1_toolchain_rows.csv -- do not edit',
           '\\begin{tabularx}{\\textwidth}{@{}l>{\\raggedright\\arraybackslash}p{0.25\\textwidth}>{\\raggedright\\arraybackslash}X>{\\raggedright\\arraybackslash}X l@{}}', '\\toprule',
           'Regime & Pinned environment & Metered quantity & Priced components of verifier work & Role \\\\', '\\midrule']
    for key in ('evm-osaka', 'eravm-29', 'zkos-v32', 'eravm-27'):
        name, tool_role, token, metered, comps = DESCRIPTORS[key]
        r = rows[tool_role]
        if token not in (r['version_pin'] + ' ' + r['used_for']).replace('`', '').replace('**', ''):
            raise SystemExit(f'T1: pin token {token!r} not found in the frozen toolchain row {tool_role!r}')
        cls = r['class'].replace('**', '')
        role = ROLE_FROM_PIN[token]
        if role not in cls:
            raise SystemExit(f'T1: role {role} not in the frozen class {cls!r} of {tool_role}')
        if key == 'evm-osaka':
            env = f"{md(r['tool'])}, hardfork osaka"
        elif key.startswith('eravm'):
            env = f"{md(r['tool'])} {md(r['version_pin']).split(' (')[0]}, protocol {token.split()[-2] if token[0].isdigit() else token.split()[1]}"
        else:
            vm = rows['ZKsync OS VM']
            env = f"{md(r['tool'])} {md(r['version_pin']).split(' prebuilt')[0]}, local chain v32.0; VM {md(vm['version_pin']).split(' (')[0]}"
        label = role.lower() + (' (historical, local)' if key == 'eravm-27' else '')
        out.append(f'{name} & {env} & {metered} & {comps} & {label} \\\\')
    out += ['\\bottomrule', '\\end{tabularx}']
    return '\n'.join(out) + '\n'

def fx(s):   # analytic template expressions -> LaTeX math
    s = s.strip()
    s = re.sub(r'ceil\(\((.*?)\)/136\)', r'\\lceil (\1)/136 \\rceil', s)
    s = s.replace('2k+1', '2k+1')
    return f'${s}$'

def t2():
    R = {r['symbol']: r for r in read('t2_operation_structure.csv')}
    def split(spec):
        d = {}
        for part in spec.split(';'):
            part = part.strip(); m = re.match(r'(G16|PLONK|FFLONK):?\s+(.*)', part)
            if not m:
                raise SystemExit(f'T2: cannot parse {part!r}')
            d[m.group(1)] = m.group(2)
        return d
    lines = [('EC scalar multiplications (ecMul)', 'n_ecMul(b,k)', 'value_P'), ('EC additions (ecAdd)', 'n_ecAdd(b,k)', 'value_P'),
             ('Pairing pairs (one call)', 'n_pair(b)', 'value_P'), ('Keccak-f rounds of the transcript', 'rho_b(k)', 'source'),
             ('Precompile calls (ZKsync OS)', 'ncalls_b(k)', 'source')]
    out = ['% GENERATED by tables/src/make_tables.py from generated/data/t2_operation_structure.csv -- do not edit',
           '\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}}lccc@{}}', '\\toprule',
           'Per verification & Groth16 & PLONK & FFLONK$^{\\dagger}$ \\\\', '\\midrule']
    for label, sym, col in lines:
        d = split(R[sym][col]); out.append(f"{label} & {fx(d['G16'])} & {fx(d['PLONK'])} & {fx(d['FFLONK'])} \\\\")
    cd = R['cd(b,k,j)']
    out.append(f"Calldata bytes & \\multicolumn{{3}}{{c}}{{{md(cd['value_P'])}, from the frozen corpus ({md(cd['uncertainty'])})}} \\\\")
    out += ['\\bottomrule', '\\end{tabular*}']
    return '\n'.join(out) + '\n'

TEXFIX = [(r'tau_cond\(F\)', r'$\\tau_{\\mathrm{cond}}^{F}$'), (r'tau_cond', r'$\\tau_{\\mathrm{cond}}$'), (r'\|e\|', r'$|e|$'), (r' x ', r' $\\times$ '),
          (r'R_pad', r'$R_{\\mathrm{pad}}$'), (r'R_anchor', r'$R_{\\mathrm{anchor}}$'), (r'%', r'\\%'), (r'<=', r'$\\le$'), (r'k = ', r'$k$ = ')]
def tex(s):
    for a, b in TEXFIX:
        s = re.sub(a, b, s)
    return s

def t3():
    R = {r['test']: r for r in read('t3_registered_tests.csv')}
    groups = [('C1 hypotheses (internal pre-registration)', ['H1', 'H2', 'H3', 'H4', 'H5', 'H6', 'H7', 'H8']),
              ('C1 prediction procedures', ['FP', 'R']),
              ('Separate test (prospective, frozen after F4; not part of C1)', ['C2']),
              ('Supporting analysis (prover; not a research question)', ['D1'])]
    if sorted(R) != sorted(t for _, g in groups for t in g):
        raise SystemExit('T3: test set differs from the generated rows')
    name = {'FP': 'P', 'R': 'R'}
    out = ['% GENERATED by tables/src/make_tables.py from generated/data/t3_registered_tests.csv -- do not edit',
           '\\begin{tabularx}{\\textwidth}{@{}l l l >{\\raggedright\\arraybackslash}p{0.17\\textwidth} >{\\raggedright\\arraybackslash}p{0.10\\textwidth} >{\\raggedright\\arraybackslash}X >{\\raggedright\\arraybackslash}p{0.13\\textwidth}@{}}',
           '\\toprule', 'Test & RQ & Role & Registration & Falsifier / criterion & Registered result & Outcome \\\\']
    for gi, (gtitle, tests) in enumerate(groups):
        out.append('\\midrule' if gi < 2 else '\\midrule[\\heavyrulewidth]')
        out.append(f'\\multicolumn{{7}}{{@{{}}l}}{{\\textit{{{gtitle}}}}} \\\\')
        for t in tests:
            r = R[t]
            out.append(' & '.join([name.get(t, t), r['rq'], r['class'].lower(), tex(r['registration']), tex(r['falsifier_or_criterion']), tex(r['result']),
                                   ('\\textbf{' + r['reader_outcome'] + '}') if r['reader_outcome'].startswith('Falsified') else r['reader_outcome']]) + ' \\\\')
    out += ['\\bottomrule', '\\end{tabularx}']
    return '\n'.join(out) + '\n'

def main():
    files = {'T1-regimes.tex': t1(), 'T2-structure.tex': t2(), 'T3-tests.tex': t3()}
    man = {'generator': 'tables/src/make_tables.py', 'generator_sha256': hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
           'inputs': dict(sorted(inputs.items())), 'outputs': {f'tables/{k}': hashlib.sha256(v.encode()).hexdigest() for k, v in files.items()}}
    if '--check' in sys.argv:
        bad = [k for k, v in files.items() if (OUT / k).read_text() != v]
        if bad or json.loads((OUT / 'TABLES-MANIFEST.json').read_text()) != man:
            raise SystemExit(f'TABLE CHECK FAIL: {bad or "manifest"}')
        print('TABLE CHECK PASS: 3 tables reproduce byte for byte'); return
    for k, v in files.items():
        (OUT / k).write_text(v)
    (OUT / 'TABLES-MANIFEST.json').write_text(json.dumps(man, indent=1, sort_keys=True) + '\n'); print('TABLES OK:', ', '.join(files))

if __name__ == '__main__':
    main()
