"""Build Figs. 2-5, verify the exported Fig. 1 (conceptual diagram authored in draw.io; figures/FIG1-EXPORT.json) and
record provenance + vector gates of all five figures in figures/FIGURES-MANIFEST.json (script paths relative to analysis/).
Usage: python3 analysis/figures/src/build_figures.py [--check]   (--check: rebuild in place and require byte-identical outputs)
Gates per PDF: every font embedded, no Type 3 font, zero raster images (pdffonts / pdfimages)."""
import hashlib, importlib, json, subprocess, sys
from pathlib import Path
import matplotlib
sys.dont_write_bytecode = True
HERE = Path(__file__).resolve().parent; sys.path.insert(0, str(HERE))
import figstyle as S

SCRIPTS = {'Fig2': 'fig2_design_map', 'Fig3': 'fig3_crossovers', 'Fig4': 'fig4_prediction', 'Fig5': 'fig5_prover'}
sha = lambda p: hashlib.sha256(Path(p).read_bytes()).hexdigest()

def gates(pdf):
    f = subprocess.run(['pdffonts', str(pdf)], capture_output=True, text=True, check=True).stdout.splitlines()[2:]
    fonts = [{'name': l.split()[0], 'type': ' '.join(l.split()[1:-5]), 'emb': l.split()[-5]} for l in f if l.strip()]
    im = subprocess.run(['pdfimages', '-list', str(pdf)], capture_output=True, text=True, check=True).stdout.splitlines()[2:]
    ok = all(x['emb'] == 'yes' and 'Type 3' not in x['type'] for x in fonts) and len([l for l in im if l.strip()]) == 0
    return {'fonts': fonts, 'raster_images': len([l for l in im if l.strip()]), 'pass': ok}

def svg_gates(svg):
    t = Path(svg).read_text(encoding='utf-8'); n = lambda tag: t.count('<' + tag + ' ') + t.count('<' + tag + '>')
    g = {'text': n('text'), 'image': n('image'), 'foreignObject': n('foreignObject'), 'data_uri': t.count('data:'), 'adaptive_colours': 'light-dark(' in t}
    g['pass'] = g['text'] > 0 and g['image'] == 0 and g['foreignObject'] == 0 and g['data_uri'] == 0
    return g

def fig1():
    """Fig. 1 is a conceptual diagram (no data, no result values) authored in draw.io; it is not generated by a script.
    The export record must match the published source and outputs; the exported PDF and SVG pass the same vector gates."""
    rec = json.loads((S.FIGDIR / 'FIG1-EXPORT.json').read_text())
    if sha(S.ROOT / rec['source']) != rec['source_sha256']:
        raise SystemExit('Fig. 1: Fig1.drawio differs from the recorded source')
    for f, h in rec['authoritative_outputs'].items():
        if sha(S.ROOT / f) != h:
            raise SystemExit(f'Fig. 1: {f} differs from the recorded export hash')
    return {'source': rec['source'], 'source_sha256': rec['source_sha256'], 'export': rec['export'], 'outputs': rec['authoritative_outputs'],
            'pdf_gates': gates(S.FIGDIR / 'Fig1.pdf'), 'svg_gates': svg_gates(S.FIGDIR / 'Fig1.svg'), 'authoritative': True}

def main():
    check = '--check' in sys.argv
    old = json.loads((S.FIGDIR / 'FIGURES-MANIFEST.json').read_text()) if check else None
    rec = {'generator': 'figures/src/build_figures.py', 'rule': 'plotting code is not analysis code; inputs: generated/data only',
           'matplotlib': matplotlib.__version__, 'style': {'file': 'figures/src/figstyle.py', 'sha256': sha(HERE / 'figstyle.py')},
           'fonts': {k: {'file': str(v), 'sha256': sha(v)} for k, v in S.FONT_FILES.items()}, 'figures': {}}
    allok = True
    for fig, mod in SCRIPTS.items():
        S._inputs.clear(); m = importlib.import_module(mod); outs = m.main()
        g = gates(S.FIGDIR / f'{fig}.pdf'); allok &= g['pass']
        rec['figures'][fig] = {'script': f'figures/src/{mod}.py', 'script_sha256': sha(HERE / f'{mod}.py'), 'inputs': {f'generated/data/{k}': v for k, v in S.inputs_read().items()},
                               'outputs': {f'figures/{k}': v for k, v in outs.items()}, 'pdf_gates': g, 'svg_gates': svg_gates(S.FIGDIR / f'{fig}.svg')}
        allok &= rec['figures'][fig]['svg_gates']['pass']
    rec['figures']['Fig1'] = f1 = fig1()
    allok &= f1['pdf_gates']['pass'] and f1['svg_gates']['pass']
    if not allok:
        raise SystemExit('VECTOR GATE FAIL: ' + json.dumps({k: v['pdf_gates'] for k, v in rec['figures'].items()}, indent=1))
    if check:
        diff = [k for k in set(rec['figures']) | set(old['figures']) if rec['figures'].get(k) != old['figures'].get(k)]
        if diff or rec['style'] != old['style']:
            raise SystemExit(f'FIGURE CHECK FAIL: outputs or provenance differ for {diff or "style"}')
        print(f'FIGURE CHECK PASS: {len(rec["figures"]) - ("Fig1" in rec["figures"])} figures reproduce byte for byte' + '; Fig. 1 export hashes verified' + '; vector gates pass'); return
    (S.FIGDIR / 'FIGURES-MANIFEST.json').write_text(json.dumps(rec, indent=1, sort_keys=True) + '\n')
    print(f'FIGURES OK: {", ".join(sorted(rec["figures"]))}; vector gates pass; manifest written')

if __name__ == '__main__':
    main()
