#!/usr/bin/env python3
"""Regenerate the PLONK proving keys classified REGENERABLE and validate them against their frozen SHA-256.

`snarkjs plonk setup` takes no contribution: given the same R1CS, the same powers-of-tau file and the same snarkjs
version it produces the same key byte for byte. The keys are therefore not stored; this script rebuilds them from the
published R1CS files and setup/ptau/pot16_final.ptau with snarkjs 0.7.5 (pinned by package-lock.json and by the
SHA-256 of the installed snarkjs files) and checks every result against provenance/REGENERABLE.tsv.

usage:
  python3 scripts/regenerate_keys.py [--work DIR] [--snarkjs-dir DIR] [--place] [--only PATH ...]
    --work         work directory outside the artifact (default: a new temporary directory)
    --snarkjs-dir  an existing node_modules/snarkjs directory to use instead of installing the pinned one (npm ci)
    --place        copy each validated key to its published path (afterwards Level 1 reports it PRESENT HASH-MATCH)
    --only         regenerate only the listed published paths
Requires node and npm (network access for npm ci, unless --snarkjs-dir is given). The largest keys need several GB
of memory; NODE_OPTIONS=--max-old-space-size=8192 is set.
"""
import argparse, csv, hashlib, io, os, shutil, subprocess, sys, tempfile
from pathlib import Path

A = Path(__file__).resolve().parents[1]
KIT = A / 'protocols/prover-d1/kit'                    # package.json / package-lock.json pinning snarkjs 0.7.5
PINNED = {'package.json': '5574a6c1e1c4770da0bad3bcd44cc6af8d4a84871802553acb328385294fb084',   # protocols/c1-preregistration/toolchain/PINS-C1.txt
          'build/main.cjs': 'e99bbb85ee536fd64476f87492665d1a382e930e4e412278a3fd8e2f987c283f',
          'cli.js': 'ce5d4938e03a798a416d062f0b689b8d0220d36ab1feea34618211b241082a53'}


def sha256(p):
    h = hashlib.sha256()
    with open(p, 'rb') as f:
        for chunk in iter(lambda: f.read(1 << 20), b''):
            h.update(chunk)
    return h.hexdigest()


def snarkjs(work, given):
    d = Path(given) if given else work / 'node' / 'node_modules' / 'snarkjs'
    if not given and not d.exists():
        (work / 'node').mkdir(parents=True, exist_ok=True)
        for f in ('package.json', 'package-lock.json'):
            shutil.copy2(KIT / f, work / 'node' / f)
        subprocess.run(['npm', 'ci', '--ignore-scripts', '--no-audit', '--no-fund'], cwd=work / 'node', check=True)
    bad = [f for f, h in PINNED.items() if not (d / f).is_file() or sha256(d / f) != h]
    if bad:
        raise SystemExit(f'snarkjs at {d} is not the pinned snarkjs 0.7.5 (differs: {bad})')
    return d / 'cli.js'


def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--work'); ap.add_argument('--snarkjs-dir'); ap.add_argument('--place', action='store_true')
    ap.add_argument('--only', nargs='*'); a = ap.parse_args()
    rows = list(csv.DictReader(io.StringIO((A / 'provenance/REGENERABLE.tsv').read_text('utf-8')), delimiter='\t'))
    if a.only:
        rows = [r for r in rows if r['path'] in a.only]
    work = Path(a.work) if a.work else Path(tempfile.mkdtemp(prefix='regen-keys-'))
    if A in work.resolve().parents or work.resolve() == A:
        raise SystemExit('the work directory must be outside the artifact')
    work.mkdir(parents=True, exist_ok=True)
    cli = snarkjs(work, a.snarkjs_dir)
    env = dict(os.environ, NODE_OPTIONS=os.environ.get('NODE_OPTIONS', '--max-old-space-size=8192'))
    built = {}; fail = 0
    for r in rows:
        r1cs, ptau = A / r['r1cs'], A / r['ptau']
        for p, h in ((r1cs, r['r1cs_sha256']), (ptau, r['ptau_sha256'])):
            if sha256(p) != h:
                raise SystemExit(f'{p.relative_to(A)}: input hash differs from provenance/REGENERABLE.tsv')
        key = (r['r1cs'], r['ptau'])
        if key not in built:
            out = work / 'keys' / (r['r1cs'].replace('/', '__') + '.zkey'); out.parent.mkdir(parents=True, exist_ok=True)
            subprocess.run(['node', str(cli), 'plonk', 'setup', str(r1cs), str(ptau), str(out)], check=True, env=env, stdout=subprocess.DEVNULL)
            built[key] = out
        got = sha256(built[key]); ok = got == r['sha256']
        fail += not ok
        print(f"{'MATCH   ' if ok else 'MISMATCH'} {r['path']}  {got}")
        if ok and a.place:
            dst = A / r['path']; dst.parent.mkdir(parents=True, exist_ok=True); shutil.copy2(built[key], dst)
    print(f'{len(rows) - fail} / {len(rows)} keys regenerated byte-identical; work directory {work}')
    return 1 if fail else 0


if __name__ == '__main__':
    sys.exit(main())
